-- Naver Shopping API Integration - DDL
-- 모든 테이블은 멱등성 보장 (IF NOT EXISTS)

-- 1. 검색 실행 그룹
CREATE TABLE IF NOT EXISTS shopping_search_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT,
    search_purpose VARCHAR(30) NOT NULL DEFAULT 'REPORT_PREPARE',
    original_query VARCHAR(500) NOT NULL,
    base_product_name VARCHAR(500),
    base_price INTEGER,
    base_category1 VARCHAR(100),
    base_category2 VARCHAR(100),
    base_category3 VARCHAR(100),
    base_category4 VARCHAR(100),
    total_fetched_count INTEGER NOT NULL DEFAULT 0,
    deduplicated_count INTEGER NOT NULL DEFAULT 0,
    candidate_count INTEGER NOT NULL DEFAULT 0,
    representative_sort VARCHAR(10) NOT NULL DEFAULT 'sim',
    collected_at TIMESTAMP NOT NULL DEFAULT NOW(),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 2. Query variant
CREATE TABLE IF NOT EXISTS shopping_query_variant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    search_group_id BIGINT NOT NULL REFERENCES shopping_search_group(id),
    query VARCHAR(500) NOT NULL,
    query_type VARCHAR(30) NOT NULL DEFAULT 'ORIGINAL',
    priority INTEGER NOT NULL DEFAULT 1,
    fallback_used BOOLEAN NOT NULL DEFAULT FALSE,
    result_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 3. API 호출 snapshot
CREATE TABLE IF NOT EXISTS shopping_search_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    search_group_id BIGINT NOT NULL REFERENCES shopping_search_group(id),
    query_variant_id BIGINT,
    source VARCHAR(30) NOT NULL DEFAULT 'NAVER_SHOPPING',
    query VARCHAR(500) NOT NULL,
    sort VARCHAR(10) NOT NULL DEFAULT 'sim',
    display INTEGER NOT NULL DEFAULT 100,
    start INTEGER NOT NULL DEFAULT 1,
    total_count INTEGER NOT NULL DEFAULT 0,
    collected_at TIMESTAMP NOT NULL DEFAULT NOW(),
    raw_response_json JSONB,
    raw_response_storage_path TEXT,
    success BOOLEAN NOT NULL DEFAULT TRUE,
    error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 4. 수집 상품 snapshot
CREATE TABLE IF NOT EXISTS shopping_product_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    search_group_id BIGINT NOT NULL REFERENCES shopping_search_group(id),
    search_snapshot_id BIGINT NOT NULL REFERENCES shopping_search_snapshot(id),
    query_variant_id BIGINT,
    source VARCHAR(30) NOT NULL DEFAULT 'NAVER_SHOPPING',
    external_product_id VARCHAR(100),
    deduplication_key VARCHAR(500),
    title_raw TEXT,
    title_clean TEXT,
    normalized_title TEXT,
    product_url TEXT,
    image_url TEXT,
    lprice INTEGER,
    hprice INTEGER,
    mall_name VARCHAR(200),
    product_type VARCHAR(20),
    brand_raw VARCHAR(200),
    brand_normalized VARCHAR(200),
    maker_raw VARCHAR(200),
    maker_normalized VARCHAR(200),
    category1 VARCHAR(100),
    category2 VARCHAR(100),
    category3 VARCHAR(100),
    category4 VARCHAR(100),
    original_rank INTEGER,
    sort_type VARCHAR(10) NOT NULL DEFAULT 'sim',
    data_quality_score INTEGER NOT NULL DEFAULT 0,
    data_confidence VARCHAR(10) NOT NULL DEFAULT 'LOW',
    collected_at TIMESTAMP NOT NULL DEFAULT NOW(),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 5. 중복 제거 로그
CREATE TABLE IF NOT EXISTS shopping_product_dedup_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    search_group_id BIGINT NOT NULL,
    kept_product_snapshot_id BIGINT NOT NULL,
    removed_product_snapshot_id BIGINT NOT NULL,
    deduplication_method VARCHAR(50) NOT NULL,
    deduplication_reason TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 6. 후보 상품
CREATE TABLE IF NOT EXISTS shopping_candidate_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    search_group_id BIGINT NOT NULL REFERENCES shopping_search_group(id),
    report_id BIGINT,
    product_snapshot_id BIGINT NOT NULL REFERENCES shopping_product_snapshot(id),
    candidate_score DECIMAL(6,2) NOT NULL DEFAULT 0,
    category_match_score DECIMAL(6,2) NOT NULL DEFAULT 0,
    title_similarity_score DECIMAL(6,2) NOT NULL DEFAULT 0,
    price_range_score DECIMAL(6,2) NOT NULL DEFAULT 0,
    brand_presence_score DECIMAL(6,2) NOT NULL DEFAULT 0,
    rank_score DECIMAL(6,2) NOT NULL DEFAULT 0,
    data_quality_score INTEGER NOT NULL DEFAULT 0,
    data_confidence VARCHAR(10) NOT NULL DEFAULT 'LOW',
    scoring_version VARCHAR(50),
    scoring_detail_json JSONB,
    candidate_reason TEXT,
    is_selected_by_user BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 7. 후보 역할 (다중)
CREATE TABLE IF NOT EXISTS shopping_candidate_product_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_product_id BIGINT NOT NULL REFERENCES shopping_candidate_product(id),
    role_type VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 8. 시장 분석 snapshot
CREATE TABLE IF NOT EXISTS shopping_market_analysis_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    search_group_id BIGINT NOT NULL REFERENCES shopping_search_group(id),
    analysis_version VARCHAR(30) NOT NULL DEFAULT 'NAVER_SHOPPING_MARKET_V1',
    representative_sort VARCHAR(10) NOT NULL DEFAULT 'sim',
    price_analysis_json JSONB,
    low_price_benchmark_json JSONB,
    high_price_benchmark_json JSONB,
    recent_product_summary_json JSONB,
    brand_distribution_json JSONB,
    maker_distribution_json JSONB,
    mall_distribution_json JSONB,
    category_distribution_json JSONB,
    dominant_category_json JSONB,
    category_mixed BOOLEAN NOT NULL DEFAULT FALSE,
    dominant_category_confidence DECIMAL(5,2),
    report_context_json JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 인덱스
CREATE INDEX IF NOT EXISTS idx_ssg_report_id ON shopping_search_group(report_id);
CREATE INDEX IF NOT EXISTS idx_sqv_search_group ON shopping_query_variant(search_group_id);
CREATE INDEX IF NOT EXISTS idx_sss_search_group ON shopping_search_snapshot(search_group_id);
CREATE INDEX IF NOT EXISTS idx_sps_search_group ON shopping_product_snapshot(search_group_id);
CREATE INDEX IF NOT EXISTS idx_sps_external_id ON shopping_product_snapshot(external_product_id);
CREATE INDEX IF NOT EXISTS idx_scp_search_group ON shopping_candidate_product(search_group_id);
CREATE INDEX IF NOT EXISTS idx_scpr_candidate ON shopping_candidate_product_role(candidate_product_id);
CREATE INDEX IF NOT EXISTS idx_smas_search_group ON shopping_market_analysis_snapshot(search_group_id);
