-- Report generation job queue.
-- Purpose: make the monolith worker-ready before extracting a report-worker service.

CREATE TABLE IF NOT EXISTS report_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_order_id BIGINT NOT NULL REFERENCES report_order(id),
    job_type VARCHAR(50) NOT NULL DEFAULT 'DETAIL_PAGE_REPORT',
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    force_regenerate BOOLEAN NOT NULL DEFAULT FALSE,
    has_images BOOLEAN NOT NULL DEFAULT FALSE,
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 3,
    locked_by VARCHAR(120),
    locked_until TIMESTAMP,
    heartbeat_at TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    failure_type VARCHAR(50),
    next_retry_at TIMESTAMP,
    error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE report_job ADD COLUMN IF NOT EXISTS failure_type VARCHAR(50);
ALTER TABLE report_job ADD COLUMN IF NOT EXISTS next_retry_at TIMESTAMP;

CREATE TABLE IF NOT EXISTS report_job_step (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES report_job(id) ON DELETE CASCADE,
    step_key VARCHAR(60) NOT NULL,
    step_order INTEGER NOT NULL,
    step_name VARCHAR(120) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_report_job_claim
    ON report_job (status, locked_until, created_at, id);

CREATE INDEX IF NOT EXISTS idx_report_job_retry_claim
    ON report_job (status, next_retry_at, locked_until, created_at, id);

CREATE INDEX IF NOT EXISTS idx_report_job_order_created
    ON report_job (report_order_id, created_at DESC, id DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uk_report_job_one_active_per_order
    ON report_job (report_order_id)
    WHERE status IN ('PENDING', 'RUNNING', 'STOP_REQUESTED');

CREATE UNIQUE INDEX IF NOT EXISTS uk_report_job_step_job_key
    ON report_job_step (job_id, step_key);

CREATE INDEX IF NOT EXISTS idx_report_job_step_job_order
    ON report_job_step (job_id, step_order);
