#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET_DIR="${1:-"${ROOT_DIR}/../PreCustomerMSA"}"

if [[ -e "${TARGET_DIR}" ]] && [[ -n "$(find "${TARGET_DIR}" -mindepth 1 -maxdepth 1 -print -quit 2>/dev/null)" ]]; then
  echo "Target directory is not empty: ${TARGET_DIR}" >&2
  echo "Choose a new path or remove it yourself before exporting." >&2
  exit 1
fi

mkdir -p "${TARGET_DIR}"

copy_gradle_scaffold() {
  local repo_dir="$1"
  mkdir -p "${repo_dir}"
  cp -R "${ROOT_DIR}/gradle" "${repo_dir}/"
  cp "${ROOT_DIR}/gradlew" "${repo_dir}/"
  cp "${ROOT_DIR}/gradlew.bat" "${repo_dir}/"
  cp "${ROOT_DIR}/.gitignore" "${repo_dir}/"
}

init_repo() {
  local repo_dir="$1"
  local subject="$2"
  local body="$3"

  (
    cd "${repo_dir}"
    if git init -b main >/dev/null 2>&1; then
      :
    else
      git init >/dev/null
      git checkout -B main >/dev/null
    fi
    git add -A
    git -c user.name="PreCustomer Export" \
      -c user.email="precustomer@example.invalid" \
      commit -m "${subject}" -m "${body}" >/dev/null
  )
}

write_settings() {
  local repo_dir="$1"
  local root_name="$2"
  local include_contracts="$3"

  cat > "${repo_dir}/settings.gradle" <<SETTINGS
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        mavenLocal()
    }
}

rootProject.name = '${root_name}'
SETTINGS

  if [[ "${include_contracts}" == "true" ]]; then
    cat >> "${repo_dir}/settings.gradle" <<'SETTINGS'

def localContracts = file('../precustomer-contracts')
if (localContracts.isDirectory()) {
    includeBuild(localContracts)
}
SETTINGS
  fi
}

write_contracts_repo() {
  local repo_dir="${TARGET_DIR}/precustomer-contracts"
  copy_gradle_scaffold "${repo_dir}"
  write_settings "${repo_dir}" "precustomer-contracts" "false"
  cp -R "${ROOT_DIR}/modules/precustomer-contracts/src" "${repo_dir}/src"

  cat > "${repo_dir}/build.gradle" <<'GRADLE'
plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

jar {
    archiveBaseName = 'precustomer-contracts'
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.3'
    testImplementation 'org.assertj:assertj-core:3.25.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.3'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
GRADLE

  cat > "${repo_dir}/README.md" <<'README'
# PreCustomer Contracts

서비스 사이에서 공유하는 작은 계약 라이브러리 repo입니다.

## Local

```bash
./gradlew test
./gradlew publishToMavenLocal
```
README

  mkdir -p "${repo_dir}/.github/workflows"
  cat > "${repo_dir}/.github/workflows/ci.yml" <<'YAML'
name: contracts-ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - run: ./gradlew test publishToMavenLocal
YAML

  init_repo \
    "${repo_dir}" \
    "feat: 서비스 계약 라이브러리 repo 분리" \
    "Gateway와 각 서비스가 공유하는 Passport 인증 계약을 독립 라이브러리로 분리했다.

Constraint: 서비스 간 공유 코드는 contracts로 제한해야 함
Confidence: high
Scope-risk: narrow
Tested: generated by tools/export-multi-repo-msa.sh"
}

write_gateway_repo() {
  local repo_dir="${TARGET_DIR}/precustomer-api-gateway"
  copy_gradle_scaffold "${repo_dir}"
  write_settings "${repo_dir}" "precustomer-api-gateway" "true"
  cp -R "${ROOT_DIR}/apps/api-gateway/src" "${repo_dir}/src"

  cat > "${repo_dir}/build.gradle" <<'GRADLE'
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation 'com.example:precustomer-contracts:0.0.1-SNAPSHOT'
    implementation 'org.springframework.cloud:spring-cloud-starter-gateway:4.1.5'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'

    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

springBoot {
    mainClass = 'com.example.personareport.gateway.ApiGatewayApplication'
}

bootJar {
    archiveBaseName = 'precustomer-api-gateway'
}

bootRun {
    args '--spring.profiles.active=local,gateway'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
GRADLE

  write_dockerfile "${repo_dir}" "precustomer-api-gateway"

  cat > "${repo_dir}/README.md" <<'README'
# PreCustomer API Gateway

Spring Cloud Gateway 기반 routing/auth 진입점 repo입니다.

## Local

같은 상위 디렉터리에 `precustomer-contracts` repo가 있으면 자동으로 composite build를 사용합니다.

```bash
ADMIN_USERNAME=admin ADMIN_PASSWORD=local-secret ./gradlew bootRun
./gradlew test bootJar
```
README

  write_service_ci "${repo_dir}" "gateway-ci" "test bootJar"

  init_repo \
    "${repo_dir}" \
    "feat: API Gateway repo 분리" \
    "Spring Cloud Gateway 기반 routing과 JWT/Passport 인증 진입점을 독립 repo로 분리했다.

Constraint: gateway는 contracts 외 공통 코드에 의존하지 않아야 함
Confidence: high
Scope-risk: moderate
Tested: generated by tools/export-multi-repo-msa.sh"
}

write_dockerfile() {
  local repo_dir="$1"
  local archive_name="$2"

  cat > "${repo_dir}/Dockerfile" <<DOCKER
FROM eclipse-temurin:17-jre

ARG JAR_FILE=build/libs/${archive_name}-0.0.1-SNAPSHOT.jar

RUN apt-get update \\
    && apt-get install -y --no-install-recommends curl \\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY \${JAR_FILE} /app/app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
DOCKER
}

write_service_ci() {
  local repo_dir="$1"
  local workflow_name="$2"
  local gradle_tasks="$3"

  mkdir -p "${repo_dir}/.github/workflows"
  cat > "${repo_dir}/.github/workflows/ci.yml" <<YAML
name: ${workflow_name}

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout service
        uses: actions/checkout@v4
      - name: Checkout contracts sibling
        uses: actions/checkout@v4
        with:
          repository: \${{ vars.CONTRACTS_REPOSITORY || 'sesungg/precustomer-contracts' }}
          path: precustomer-contracts
      - name: Link contracts as sibling for composite build
        run: ln -s "\$PWD/precustomer-contracts" ../precustomer-contracts
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - run: ./gradlew ${gradle_tasks}
YAML
}

write_service_build_gradle() {
  local repo_dir="$1"
  local main_class="$2"
  local archive_name="$3"
  local profiles="$4"

  cat > "${repo_dir}/build.gradle" <<GRADLE
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

dependencies {
    implementation 'com.example:precustomer-contracts:0.0.1-SNAPSHOT'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign:4.1.3'
    implementation 'com.querydsl:querydsl-jpa:5.1.0:jakarta'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    annotationProcessor 'com.querydsl:querydsl-apt:5.1.0:jakarta'
    annotationProcessor 'jakarta.annotation:jakarta.annotation-api'
    annotationProcessor 'jakarta.persistence:jakarta.persistence-api'

    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'org.postgresql:postgresql'

    implementation 'org.commonmark:commonmark:0.22.0'
    implementation('com.github.librepdf:openpdf:1.4.2')
    implementation('org.xhtmlrenderer:flying-saucer-pdf-openpdf:9.4.0') {
        exclude group: 'com.github.librepdf', module: 'openpdf'
    }

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

springBoot {
    mainClass = '${main_class}'
}

bootJar {
    archiveBaseName = '${archive_name}'
}

bootRun {
    args '--spring.profiles.active=${profiles}'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
GRADLE
}

write_service_repo() {
  local source_name="$1"
  local repo_name="$2"
  local root_name="$3"
  local main_class="$4"
  local archive_name="$5"
  local profiles="$6"
  local description="$7"
  local repo_dir="${TARGET_DIR}/${repo_name}"

  copy_gradle_scaffold "${repo_dir}"
  write_settings "${repo_dir}" "${root_name}" "true"
  cp -R "${ROOT_DIR}/apps/${source_name}/src" "${repo_dir}/src"

  if [[ "${source_name}" == "report-worker" ]]; then
    mkdir -p "${repo_dir}/scripts"
    cp -R "${ROOT_DIR}/scripts/pipeline" "${repo_dir}/scripts/"
  fi

  write_service_build_gradle "${repo_dir}" "${main_class}" "${archive_name}" "${profiles}"
  write_dockerfile "${repo_dir}" "${archive_name}"

  cat > "${repo_dir}/README.md" <<README
# ${root_name}

${description}

## Local

같은 상위 디렉터리에 \`precustomer-contracts\` repo가 있으면 자동으로 composite build를 사용합니다.

\`\`\`bash
./gradlew bootRun
./gradlew bootJar
java -jar build/libs/${archive_name}-0.0.1-SNAPSHOT.jar --spring.profiles.active=${profiles}
\`\`\`

contracts repo가 다른 위치에 있다면 먼저 Maven local에 publish합니다.

\`\`\`bash
cd ../precustomer-contracts
./gradlew publishToMavenLocal
cd ../${repo_name}
./gradlew bootJar
\`\`\`
README

  write_service_ci "${repo_dir}" "service-ci" "bootJar"

  init_repo \
    "${repo_dir}" \
    "feat: ${root_name} 서비스 repo 분리" \
    "공통 core 없이 ${root_name} 실행 앱과 Dockerfile을 독립 repo로 분리했다.

Constraint: 서비스 repo는 contracts 외 공통 라이브러리에 의존하지 않아야 함
Confidence: high
Scope-risk: moderate
Tested: generated by tools/export-multi-repo-msa.sh"
}

write_platform_repo() {
  local repo_dir="${TARGET_DIR}/precustomer-platform"
  mkdir -p "${repo_dir}/infra" "${repo_dir}/docs"
  cp -R "${ROOT_DIR}/infra/." "${repo_dir}/infra/"
  cp -R "${ROOT_DIR}/docs/sql" "${repo_dir}/docs/"
  cp "${ROOT_DIR}/docs/msa-six-stage-roadmap.md" "${repo_dir}/docs/"
  cp "${ROOT_DIR}/docs/report-worker-migration.md" "${repo_dir}/docs/"

  cat > "${repo_dir}/compose.msa.yml" <<'COMPOSE'
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: precustomer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infra/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d precustomer"]
      interval: 10s
      timeout: 5s
      retries: 10

  public-web:
    build:
      context: ../precustomer-public-web
      args:
        JAR_FILE: build/libs/precustomer-public-web-0.0.1-SNAPSHOT.jar
    environment:
      SPRING_PROFILES_ACTIVE: prod,public-web
      DATABASE_URL: jdbc:postgresql://postgres:5432/precustomer
      DATABASE_USERNAME: ${PUBLIC_DB_USERNAME:-precustomer_public_web}
      DATABASE_PASSWORD: ${PUBLIC_DB_PASSWORD:-public-local}
      PUBLIC_PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/actuator/health/readiness >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 12

  admin-web:
    build:
      context: ../precustomer-admin-web
      args:
        JAR_FILE: build/libs/precustomer-admin-web-0.0.1-SNAPSHOT.jar
    environment:
      SPRING_PROFILES_ACTIVE: prod,admin-web
      DATABASE_URL: jdbc:postgresql://postgres:5432/precustomer
      DATABASE_USERNAME: ${ADMIN_DB_USERNAME:-precustomer_admin_web}
      DATABASE_PASSWORD: ${ADMIN_DB_PASSWORD:-admin-local}
      ADMIN_PORT: 8081
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-change-me-before-prod}
      GATEWAY_PASSPORT_SECRET: ${GATEWAY_PASSPORT_SECRET:-local-passport-secret-change-me-32bytes!}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8081/actuator/health/readiness >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 12

  report-worker:
    build:
      context: ../precustomer-report-worker
      args:
        JAR_FILE: build/libs/precustomer-report-worker-0.0.1-SNAPSHOT.jar
    environment:
      SPRING_PROFILES_ACTIVE: prod,worker
      DATABASE_URL: jdbc:postgresql://postgres:5432/precustomer
      DATABASE_USERNAME: ${WORKER_DB_USERNAME:-precustomer_report_worker}
      DATABASE_PASSWORD: ${WORKER_DB_PASSWORD:-worker-local}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY:-}
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
      NAVER_SHOPPING_CLIENT_ID: ${NAVER_SHOPPING_CLIENT_ID:-}
      NAVER_SHOPPING_CLIENT_SECRET: ${NAVER_SHOPPING_CLIENT_SECRET:-}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "kill -0 1"]
      interval: 10s
      timeout: 5s
      retries: 12

  gateway:
    build:
      context: ../precustomer-api-gateway
      args:
        JAR_FILE: build/libs/precustomer-api-gateway-0.0.1-SNAPSHOT.jar
    environment:
      SPRING_PROFILES_ACTIVE: prod,gateway
      GATEWAY_PORT: 8088
      PUBLIC_WEB_URI: http://public-web:8080
      ADMIN_WEB_URI: http://admin-web:8081
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-change-me-before-prod}
      GATEWAY_JWT_SECRET: ${GATEWAY_JWT_SECRET:-local-jwt-secret-change-me-32bytes-minimum}
      GATEWAY_PASSPORT_SECRET: ${GATEWAY_PASSPORT_SECRET:-local-passport-secret-change-me-32bytes!}
      GATEWAY_JWT_SECURE_COOKIE: ${GATEWAY_JWT_SECURE_COOKIE:-false}
    ports:
      - "8088:8088"
    depends_on:
      public-web:
        condition: service_healthy
      admin-web:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8088/actuator/health/readiness >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 12

volumes:
  postgres-data:
COMPOSE

  cat > "${repo_dir}/README.md" <<'README'
# PreCustomer Platform

분리된 서비스 repo들을 로컬에서 함께 실행하기 위한 orchestration repo입니다.

## Expected sibling repos

```text
PreCustomerMSA/
  precustomer-contracts/
  precustomer-api-gateway/
  precustomer-public-web/
  precustomer-admin-web/
  precustomer-report-worker/
  precustomer-platform/
```

## Build service jars

```bash
cd ../precustomer-contracts && ./gradlew publishToMavenLocal
cd ../precustomer-api-gateway && ./gradlew bootJar
cd ../precustomer-public-web && ./gradlew bootJar
cd ../precustomer-admin-web && ./gradlew bootJar
cd ../precustomer-report-worker && ./gradlew bootJar
```

## Run gateway stack

```bash
cd ../precustomer-platform
ADMIN_USERNAME=admin \
ADMIN_PASSWORD=local-secret \
GATEWAY_JWT_SECRET=dev-jwt-secret-for-compose-32bytes-minimum \
GATEWAY_PASSPORT_SECRET=dev-passport-secret-for-compose-32bytes \
docker compose -f compose.msa.yml up --build
```
README

  mkdir -p "${repo_dir}/.github/workflows"
  cat > "${repo_dir}/.github/workflows/ci.yml" <<'YAML'
name: platform-ci

on:
  push:
  pull_request:

jobs:
  compose-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f compose.msa.yml config
YAML

  init_repo \
    "${repo_dir}" \
    "feat: 플랫폼 오케스트레이션 repo 분리" \
    "멀티 repo MSA 전환을 위해 compose와 SQL 문서를 플랫폼 repo로 분리했다.

Constraint: 서비스 repo들은 sibling path에서 Docker build context로 참조됨
Confidence: high
Scope-risk: narrow
Tested: generated by tools/export-multi-repo-msa.sh"
}

write_workspace_readme() {
  cat > "${TARGET_DIR}/README.md" <<'README'
# PreCustomer Multi-repo Workspace

이 디렉터리는 `tools/export-multi-repo-msa.sh`로 생성된 로컬 multi-repo MSA 워크스페이스입니다.

```text
precustomer-contracts/     # shared contract repo
precustomer-api-gateway/   # gateway/auth repo
precustomer-public-web/    # customer-facing web service repo
precustomer-admin-web/     # admin web service repo
precustomer-report-worker/ # report job worker service repo
precustomer-platform/      # compose and SQL orchestration repo
```

## Verify

```bash
cd precustomer-contracts && ./gradlew test
cd ../precustomer-api-gateway && ./gradlew bootJar
cd ../precustomer-public-web && ./gradlew bootJar
cd ../precustomer-admin-web && ./gradlew bootJar
cd ../precustomer-report-worker && ./gradlew bootJar
```
README
}

write_contracts_repo
write_gateway_repo
write_service_repo "public-web" "precustomer-public-web" "precustomer-public-web" "com.example.personareport.PublicWebApplication" "precustomer-public-web" "local,public-web" "사용자 랜딩/리포트 신청 화면을 담당하는 public web 서비스 repo입니다."
write_service_repo "admin-web" "precustomer-admin-web" "precustomer-admin-web" "com.example.personareport.AdminWebApplication" "precustomer-admin-web" "local,admin-web" "관리자 주문/리포트/MV/쇼핑 관리 화면을 담당하는 admin web 서비스 repo입니다."
write_service_repo "report-worker" "precustomer-report-worker" "precustomer-report-worker" "com.example.personareport.ReportWorkerApplication" "precustomer-report-worker" "local,worker" "report_job 큐를 처리하고 리포트 파이프라인을 실행하는 worker 서비스 repo입니다."
write_platform_repo
write_workspace_readme

echo "Multi-repo MSA workspace exported to: ${TARGET_DIR}"
